### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by paultrott** [farizrahman4u/loopgpt#34]
Error reading a .h file.
---
SYSTEM: Executing command: read_from_file
Traceback (most recent call last):
  File "/home/xxx/loopgpt/research_gpt.py", line 14, in <module>
    agent.cli()
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/loopgpt/agent.py", line 501, in cli
    cli(self, continuous=continuous)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/loopgpt/loops/repl.py", line 174, in cli
    resp = agent.chat(run_tool=True)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/loopgpt/utils/spinner.py", line 137, in inner
    return func(*args, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/loopgpt/agent.py", line 185, in chat
    assert max_tokens
AssertionError

**Comment by FayazRahman** [comment]
@paultrott This happens when the file you are reading is too big, we have not yet implemented input chunking
